import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Evelocore Editor",
  description: "Generated by K.Prabhasha",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <link rel="icon" href="/media/icon.jpg" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="/styles/home/home.css" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.1.0/css/boxicons.min.css"/>
      <link rel="stylesheet" href="/styles/theme.css" />
      <link rel="stylesheet" href="/styles/header.css" />
      <link rel="stylesheet" href="/styles/loading.css" />
      <link rel="stylesheet" href="/styles/slide-nav.css" />
      <link rel="stylesheet" href="/styles/screen.css" />
      <link rel="stylesheet" href="/styles/editor.css" />
      <link rel="stylesheet" href="/styles/select-input.css" />
      <link rel="stylesheet" href="/styles/switch.css" />
      <link rel="stylesheet" href="/styles/scroll.css" />
      <link rel="stylesheet" href="/styles/notification.css" />
      <link rel="stylesheet" href="/styles/addfiles.css" />
      <link rel="stylesheet" href="/styles/console.css" />
      
    </head>
      <body>{children}</body>
    </html>
  );
}
